def exception(val):
    if val == True:
        raise RuntimeError("Lanzo esta excepci√≥n")
    else:
        return 0